### ISSUE TITLE
Ability to specify in Arlifile the destination folder relative to Arlifile

### ISSUE THREAD

**Issue by kigster** [kigster/arli#4]
Right now Arlifile looks like this:

```yaml
# vi:syntax=yaml
version: 1.0.0
dependencies:
  - name: "Adafruit Unified Sensor"
  - name: "Time"
  - name: "Adafruit GFX Library"
```

Let's add additional metadata:

```yaml
# vi:syntax=yaml
version: 1.0.0
  bundle:
     lib_path: libraries
     format: cmake
dependencies:
  - name: "Adafruit Unified Sensor"
  - name: "Time"
  - name: "Adafruit GFX Library"
```
